### ISSUE TITLE
plugin failing to run

### ISSUE THREAD

**Issue by switchalls** [ipastusi/wiremock-maven-plugin#41]
Mac 10.14.4 / Jdk 1.8.0_192 / Maven 3.6.0
POM parent is spring-boot 1.5.17.RELEASE
Plugin: 4.4.0

Added plugin as per README

Project uses Saxon: 9.1.0.8

Plugin execution failing ; see attached stacktrace

junits use XPaths and {cargo-maven2-plugin, soapui-maven-plugin} plugins run, so pom looks OK.

[wiremock-plugin-stacktrace.txt](https://github.com/automatictester/wiremock-maven-plugin/files/3188840/wiremock-plugin-stacktrace.txt)

**Comment by switchalls** [comment]
Not sure if it helps, but seeing output below with exception

Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[project>uk.co.xxxxxxxxx:5.10.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

**Comment by switchalls** [comment]
I've done some digging and the "Illegal configuration-file syntax" error looks like a known saxon issue, eg. https://saxonica.plan.io/issues/1944

Is there a way to exclude the saxon jars from wiremock plugin execution?

I've had a look at the maven docs, but cannot see what I've got to do

**Comment by automatictester** [comment]
Hi. Would you be able to provide a reproducible test case?

**Comment by switchalls** [comment]
Added project as requested. Run "mvn clean install"

I've left all 3rd party dependencies in so you can see them. But stripped back some of the plugins (eg. cargo) as the error happens anyway.

The plugin is displaying:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.197 s
[INFO] Finished at: 2019-05-17T19:42:02+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal uk.co.automatictester:wiremock-maven-plugin:4.4.0:run (default) on project wiremock-plugin-saxon: Execution default of goal uk.co.automatictester:wiremock-maven-plugin:4.4.0:run failed: An API incompatibility was encountered while executing uk.co.automatictester:wiremock-maven-plugin:4.4.0:run: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>uk.co.automatictester:wiremock-maven-plugin:4.4.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/stewartw/.m2/repository/uk/co/automatictester/wiremock-maven-plugin/4.4.0/wiremock-maven-plugin-4.4.0.jar
...
[ERROR] urls[95] = file:/Users/stewartw/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.jar
[ERROR] urls[96] = file:/Users/stewartw/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-dom.jar
[ERROR] urls[97] = file:/Users/stewartw/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/Users/stewartw/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax

Looks like its searching my local .m2 repo?

[wiremock-saxon.zip](https://github.com/automatictester/wiremock-maven-plugin/files/3192676/wiremock-saxon.zip)

**Comment by automatictester** [comment]
As you said, there seems to be a problem with `saxon`. The newer version of this dependency is not available in Maven Central. Would using a newer version of `saxon-he` instead solve this problem for you?

**Comment by switchalls** [comment]
Cannot use newer version at mo as it requires stylesheet changes (owned by
different department).

Can we stop the search? Why is doing the url[x] = stuff?

**Comment by automatictester** [comment]
From what I can see, problem is gone if you add this dependency:

        <dependency>
            <groupId>xalan</groupId>
            <artifactId>xalan</artifactId>
            <version>2.7.2</version>
        </dependency>

Could you please double-check?

**Comment by switchalls** [comment]
Awesome. That fixed it.

Plugin setup now:

           <plugin>
              <groupId>uk.co.automatictester</groupId>
              <artifactId>wiremock-maven-plugin</artifactId>
              <version>4.4.0</version>
              <dependencies>
                  <dependency>
                     <groupId>xalan</groupId>
                     <artifactId>xalan</artifactId>
                     <version>${xalan.version}</version>
                  </dependency>
              </dependencies>

Not sure why, but then had to also add as dependency on cargo-maven2-plugin ??!!

But ... wiremock is booting and cargo is running.

Many thanks for help. Closing this log as fixed

**Comment by automatictester** [comment]
I have released version 4.4.1 with Xalan dependency included.
