### ISSUE TITLE
Can't handle root directory with space in path

### ISSUE THREAD

**Issue by ghoover** [ipastusi/wiremock-maven-plugin#7]
A project with a path containing a space causes WireMock to load with an incorrect root directory.  

This may happen for a project without spaces in the path but with <dir> parameter with a space though (not verified).

**Comment by automatictester** [comment]
Thanks for reporting @ghoover. This has been fixed now. Fix is included in version 2.6.1 which has just been released and should be available in Maven Central in next couple of hours.
