### ISSUE TITLE
Plugin DependencyManagement overrides Wiremock dependencies

### ISSUE THREAD

**Issue by IRQs** [ipastusi/wiremock-maven-plugin#85]
Version 5.0.0 of your excellent plugin (thanks for all your work) promises to be decoupled from the WireMock version itself. However, the plugin's POM still contains a dependencyManagement section that overrides some of WireMock's own dependencies (e.g. the _asm_ 7.0 dependency from WireMock 2.25.1 is overwritten with version 5.2 in release 5.0.0 of the plugin).

Is there any particular reason why the plugin manages some of WireMock's transitive dependencies?

**Comment by automatictester** [comment]
Nice catch and interesting finding btw. Thanks for flagging this. With dependency scope `provided`, using `dependencyConvergence` rule of maven-enforcer-plugin doesn't make much sense, as we won't have much control over the transitive dependencies either. I removed `dependencyManagement` section and released version **5.0.1**.
