### ISSUE TITLE
Add support for skip configuration

### ISSUE THREAD

**Issue by maddenj-ie** [ipastusi/wiremock-maven-plugin#92]
Hi, I don't see a way of setting up the plugin to be skipped.  If the plugin is part of the integration test phase, it would be nice if it also respected the failsafe skipITs property or perhaps allowed a way for it to be configured.  Thanks.

**Comment by automatictester** [comment]
I have just implemented this functionality - see updated readme for details. It will be available since version `6.0.0`.
